services:
  backend-example:
    container_name: backend-example-dev
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ../../:/app:rw
    env_file:
      - ../../env/.env.dev
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    container_name: db-dev
    image: postgres:14-alpine
    env_file:
      - ../../env/.env.dev
    volumes:
      - backdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  backdata:
